version: "3.6"
services:
  spark-master:
    image: tonibous/spark-cluster-master:latest
    container_name: spark-master
    hostname: spark-master
    tty: true 
    ports:
      - 8080:8080
      - 7077:7077
    networks:
      - spark-net
  spark-worker-1:
    image: tonibous/spark-cluster-worker:latest
    container_name: spark-worker1
    hostname: spark-worker1
    tty: true 
    environment:
      - SPARK_WORKER_CORES=1
      - SPARK_WORKER_MEMORY=512m
    ports:
      - 8081:8081
    depends_on:
      - spark-master
    networks:
      - spark-net
      - hadoop-net
  jupyterlab:
    image: tonibous/jupyterlab:latest
    container_name: jupyterlab
    ports:
      - 8888:8888
      - 4040:4040
      - 4041:4041
    volumes:
      - /Users/tonibous/Documents/2-IMF/10-Trabajo-final-master/03-Notebooks:/opt/workspace
    networks:
      - spark-net
networks:
  spark-net:
    driver: bridge